web:
  build: .
  ports:
    - '9292:9292'
  environment:
    PORT: 9292

test:
  build: .
  ports:
    - '9292:9292'
  environment:
    PORT: 9292
  volumes:
    - '.:/app'
  command: bundle exec rspec
