#!/usr/bin/env ruby

require 'rack'

app, _options = Rack::Builder.new_from_string <<-EOF
$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)

require "poto"
require "poto/file_repository/google/cloud/storage"

client = Google::Cloud::Storage.new(
  project: ENV["GOOGLE_CLOUD_PROJECT_ID"],
  keyfile: ENV["GOOGLE_CLOUD_KEYFILE"]
).bucket(ENV["GOOGLE_CLOUD_STORAGE_BUCKET"])

repository = Poto::FileRepository::Google::Cloud::Storage.new(client: client)

map("/") do
  run Poto::App
end

map("/image_proxy") do
  run Poto::ImageProxy
end

map("/api") do
  run Poto::API.configure(repository: repository)
end
EOF

Rack::Server.start(
  app:  app,
  Port: ENV.fetch('PORT', 9292)
)
